# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-03 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_auto_20170803_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='my_day',
        ),
    ]
