# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-09 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_remove_time_my_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
