# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-10 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0008_auto_20170810_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=250, unique_for_month=True),
        ),
    ]
