# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-14 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20170812_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='create_user',
            new_name='creator',
        ),
    ]
