# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-14 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20170814_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='updater',
            new_name='updator',
        ),
    ]
